# Generated by Django 4.2.1 on 2023-05-15 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('placa', models.IntegerField(primary_key=True, serialize=False, verbose_name='Placa')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('referencia', models.CharField(max_length=100, verbose_name='Referencia')),
                ('especificaciones', models.TextField(default='', max_length=100, verbose_name='Especificaciones')),
                ('persona', models.CharField(default='', max_length=100, verbose_name='Persona')),
                ('observaciones', models.CharField(default='', max_length=200, verbose_name='Observaciones')),
                ('foto', models.ImageField(upload_to='fotos/', verbose_name='Foto')),
            ],
        ),
    ]
